Hethonglaptop_prj2/Hethonglaptop_prj2/Controllers/AccountsController.cs
using Hethonglaptop_prj2.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Hethonglaptop_prj2.Controllers
{
    public class AccountsController : Controller
    {
        private readonly Project2HthonglaptopvaphukienmaytinhContext _context;

        public AccountsController(Project2HthonglaptopvaphukienmaytinhContext context)
        {
            _context = context;
        }

        // GET: Accounts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Accounts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AccountId,UserName,Password,Email,Role")] Account acc)
        {
            if (ModelState.IsValid)
            {
                _context.Add(acc);
                await _context.SaveChangesAsync();
                return View("~/Views/Admin/Index.cshtml");
            }
            return View(acc);
        }

        // GET: Accounts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var acc = await _context.Accounts.FindAsync(id);
            if (acc == null) return NotFound();

            return View(acc);
        }

        // POST: Accounts/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AccountId,UserName,Password,Email,Role")] Account acc)
        {
            if (id != acc.AccountId) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(acc);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Accounts.Any(e => e.AccountId == acc.AccountId))
                        return NotFound();
                    else
                        throw;
                }
                return View("~/Views/Admin/Index.cshtml");
            }
            return View(acc);
        }

        // GET: Accounts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var acc = await _context.Accounts
                .FirstOrDefaultAsync(m => m.AccountId == id);
            if (acc == null) return NotFound();

            return View(acc);
        }

        // POST: Accounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var acc = await _context.Accounts.FindAsync(id);
            if (acc != null)
            {
                _context.Accounts.Remove(acc);
                await _context.SaveChangesAsync();
            }
            return View("~/Views/Admin/Index.cshtml");
        }

        // GET: Account/Register
        public IActionResult Register()
        {
            return View();
        }

        // POST: Account/Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(Account acc)
        {
            if (ModelState.IsValid)
            {
                // kiểm tra trùng username
                if (_context.Accounts.Any(a => a.UserName == acc.UserName))
                {
                    ModelState.AddModelError("", "Tên đăng nhập đã tồn tại!");
                    return View(acc);
                }

                _context.Add(acc);
                await _context.SaveChangesAsync();
                return RedirectToAction("Login");
            }
            return View(acc);
        }

        // GET: Account/Login
        public IActionResult Login()
        {
            return View();
        }

        // POST: Account/Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(string username, string password)
        {
            var acc = _context.Accounts.FirstOrDefault(a => a.UserName == username && a.Password == password);
            if (acc != null)
            {
                // Lưu Session
                HttpContext.Session.SetString("UserName", acc.UserName);
                HttpContext.Session.SetString("Role", acc.Role ?? "User");

                // Nếu là Admin thì chuyển đến trang Admin
                if (acc.Role != null && acc.Role.Equals("Admin", StringComparison.OrdinalIgnoreCase))
                {
                    return RedirectToAction("Index", "Admin");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            ViewBag.Error = "Sai tên đăng nhập hoặc mật khẩu!";
            return View();
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }
    }
}

Hethonglaptop_prj2/Hethonglaptop_prj2/Controllers/HoaDonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hethonglaptop_prj2.Models;

namespace Hethonglaptop_prj2.Controllers
{
    public class HoaDonsController : Controller
    {
        private readonly Project2HthonglaptopvaphukienmaytinhContext _context;

        public HoaDonsController(Project2HthonglaptopvaphukienmaytinhContext context)
        {
            _context = context;
        }

        // GET: HoaDons
        public async Task<IActionResult> Index()
        {
            var hoaDons = _context.HoaDons              
                          .Include(h => h.MaKhNavigation)
                          .Include(h => h.MaNvNavigation);
            return View(await hoaDons.ToListAsync());
        }

        // GET: HoaDons/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoaDon = await _context.HoaDons
                .Include(h => h.MaKhNavigation)
                .Include(h => h.MaNvNavigation)
                .FirstOrDefaultAsync(m => m.MaHd == id);
            if (hoaDon == null)
            {
                return NotFound();
            }

            return View(hoaDon);
        }

        // GET: HoaDons/Create
        public IActionResult Create()
        {
            ViewData["MaKh"] = new SelectList(_context.KhachHangs, "MaKh", "MaKh");
            ViewData["MaNv"] = new SelectList(_context.NhanViens, "MaNv", "MaNv");
            return View();
        }

        // POST: HoaDons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaHd,NgayLap,MaKh,MaNv,TongTien")] HoaDon hoaDon)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hoaDon);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Admin", new { tab = "hoadon" });

            }
            ViewData["MaKh"] = new SelectList(_context.KhachHangs, "MaKh", "MaKh", hoaDon.MaKh);
            ViewData["MaNv"] = new SelectList(_context.NhanViens, "MaNv", "MaNv", hoaDon.MaNv);
            return View(hoaDon);
        }

        // GET: HoaDons/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoaDon = await _context.HoaDons.FindAsync(id);
            if (hoaDon == null)
            {
                return NotFound();
            }
            ViewData["MaKh"] = new SelectList(_context.KhachHangs, "MaKh", "MaKh", hoaDon.MaKh);
            ViewData["MaNv"] = new SelectList(_context.NhanViens, "MaNv", "MaNv", hoaDon.MaNv);
            return View(hoaDon);
        }

        // POST: HoaDons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("MaHd,NgayLap,MaKh,MaNv,TongTien")] HoaDon hoaDon)
        {
            if (id != hoaDon.MaHd)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hoaDon);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HoaDonExists(hoaDon.MaHd))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Admin", new { tab = "hoadon" });

            }
            ViewData["MaKh"] = new SelectList(_context.KhachHangs, "MaKh", "MaKh", hoaDon.MaKh);
            ViewData["MaNv"] = new SelectList(_context.NhanViens, "MaNv", "MaNv", hoaDon.MaNv);
            return View(hoaDon);
        }

        // GET: HoaDons/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoaDon = await _context.HoaDons
                .Include(h => h.MaKhNavigation)
                .Include(h => h.MaNvNavigation)
                .FirstOrDefaultAsync(m => m.MaHd == id);
            if (hoaDon == null)
            {
                return NotFound();
            }

            return View(hoaDon);
        }

        // POST: HoaDons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var hoaDon = await _context.HoaDons.FindAsync(id);
            if (hoaDon != null)
            {
                _context.HoaDons.Remove(hoaDon);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Admin", new { tab = "hoadon" });

        }

        private bool HoaDonExists(string id)
        {
            return _context.HoaDons.Any(e => e.MaHd == id);
        }
    }
}

Hethonglaptop_prj2/Hethonglaptop_prj2/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hethonglaptop_prj2.Models;

namespace Hethonglaptop_prj2.Controllers
{
    public class SanPhamsController : Controller
    {
        private readonly Project2HthonglaptopvaphukienmaytinhContext _context;

        public SanPhamsController(Project2HthonglaptopvaphukienmaytinhContext context)
        {
            _context = context;
        }

        private string GenerateMaSP()
        {
            var last = _context.SanPhams
                .OrderByDescending(sp => sp.MaSp)
                .Select(sp => sp.MaSp)
                .FirstOrDefault();

            if (string.IsNullOrEmpty(last))
                return "SP01";

            string numberPart = last.Substring(2);
            int number = int.Parse(numberPart) + 1;

            return "SP" + number.ToString("D2");
        }

        // GET: SanPhams
        public async Task<IActionResult> Index()
        {
            var project2Context = _context.SanPhams.Include(s => s.MaThNavigation);
            return View(await project2Context.ToListAsync());
        }

        // GET: SanPhams/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams
                .Include(s => s.MaThNavigation)
                .FirstOrDefaultAsync(m => m.MaSp == id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // GET: SanPhams/Create
        public IActionResult Create()
        {
            ViewData["MaTh"] = new SelectList(_context.ThuongHieus, "MaTh", "MaTh");
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaSp,TenSp,Gia,SoLuong,MoTa,MaTh,Anh")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                sanPham.MaSp = GenerateMaSP();
                _context.Add(sanPham);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Admin", new { tab = "sanpham" });

            }
            ViewData["MaTh"] = new SelectList(_context.ThuongHieus, "MaTh", "MaTh", sanPham.MaTh);
            return View(sanPham);
        }

        // GET: SanPhams/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams.FindAsync(id);
            if (sanPham == null)
            {
                return NotFound();
            }
            ViewData["MaTh"] = new SelectList(_context.ThuongHieus, "MaTh", "MaTh", sanPham.MaTh);
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("MaSp,TenSp,Gia,SoLuong,MoTa,MaTh,Anh")] SanPham sanPham)
        {
            if (id != sanPham.MaSp)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sanPham);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SanPhamExists(sanPham.MaSp))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Admin", new { tab = "sanpham" });

            }
            ViewData["MaTh"] = new SelectList(_context.ThuongHieus, "MaTh", "MaTh", sanPham.MaTh);
            return View(sanPham);
        }

        // GET: SanPhams/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams
                .Include(s => s.MaThNavigation)
                .FirstOrDefaultAsync(m => m.MaSp == id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var sanPham = await _context.SanPhams.FindAsync(id);
            if (sanPham != null)
            {
                _context.SanPhams.Remove(sanPham);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Admin", new { tab = "sanpham" });

        }
        // Action tìm kiếm
        public IActionResult Search(string keyword)
        {
            if (string.IsNullOrEmpty(keyword))
            {
                return View("Index", _context.SanPhams.ToList());
            }

            var result = _context.SanPhams
                .Where(sp => sp.TenSp.Contains(keyword))
                .ToList();

            return View("Index", result); // Trả kết quả ra view Index.cshtml
        }
        private bool SanPhamExists(string id)
        {
            return _context.SanPhams.Any(e => e.MaSp == id);
        }

        
    }
}

Hethonglaptop_prj2/Hethonglaptop_prj2/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Admin Panel";
    Layout = "_Layout";
}

<div class="container-fluid">
    <div class="row flex-nowrap">
        <!-- Sidebar -->
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark text-white min-vh-100">
            <div class="d-flex flex-column align-items-sm-start px-3 pt-2 text-white">
                <a href="/" class="d-flex align-items-center mb-3 text-white text-decoration-none">
                    <span class="fs-4 fw-bold">⚙ Admin Panel</span>
                </a>
                <hr class="w-100 border-secondary" />

                <ul class="nav nav-pills flex-column mb-auto w-100">
                    <li class="nav-item">
                        <a href="#" id="btnQuanLySanPham" class="nav-link text-white">
                            <i class="fa fa-desktop me-2"></i> Quản lý sản phẩm
                        </a>
                    </li>
                    <li>
                        <a href="#" id="btnQuanLyDonHang" class="nav-link text-white">
                            <i class="fa fa-shopping-cart me-2"></i> Quản lý đơn hàng
                        </a>
                    </li>
                    <li>
                        <a href="#" id="btnQuanLyKhachHang" class="nav-link text-white">
                            <i class="fa fa-user me-2"></i> Quản lý khách hàng
                        </a>
                    </li>
                    <li>
                        <a href="#" id="btnQuanLyNhanVien" class="nav-link text-white">
                            <i class="fa fa-users me-2"></i> Quản lý nhân viên
                        </a>
                    </li>
                    <li>
                        <a href="#" id="btnQuanLyAccount" class="nav-link text-white">
                            <i class="fa fa-user-shield me-2"></i> Quản lý tài khoản
                        </a>
                    </li>
                </ul>

                <hr class="w-100 border-secondary" />
                <a asp-controller="Accounts" asp-action="Logout" class="text-white text-decoration-none mb-3">
                    <i class="fa fa-sign-out-alt me-2"></i> Đăng xuất
                </a>
            </div>
        </div>

        <!-- Main Content -->
        <div class="col py-3 bg-light" style="height: 100vh; overflow-y: auto;">
            <h2 id="pageTitle" class="fw-bold mb-4">Trang quản trị</h2>
            <div id="content-area">
                <!-- AJAX load nội dung ở đây -->
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            // Load mặc định
            $("#content-area").load("/Admin/DanhSachSanPham");
            $("#pageTitle").text("Danh sách sản phẩm");

            function loadContent(title, url) {
                $("#pageTitle").text(title);
                $("#content-area").load(url);
            }

            $("#btnQuanLySanPham").click(function (e) {
                e.preventDefault();
                loadContent("Danh sách sản phẩm", "/Admin/DanhSachSanPham");
            });

            $("#btnQuanLyDonHang").click(function (e) {
                e.preventDefault();
                loadContent("Danh sách đơn hàng", "/Admin/DanhSachDonHang");
            });

            $("#btnQuanLyKhachHang").click(function (e) {
                e.preventDefault();
                loadContent("Danh sách khách hàng", "/Admin/DanhSachKhachHang");
            });

            $("#btnQuanLyNhanVien").click(function (e) {
                e.preventDefault();
                loadContent("Danh sách nhân viên", "/Admin/DanhSachNhanVien");
            });

            $("#btnQuanLyAccount").click(function (e) {
                e.preventDefault();
                loadContent("Danh sách tài khoản", "/Admin/DanhSachAccount");
            });
        });
    </script>

    <style>
        .nav-link:hover,
        .nav-link.active {
            background-color: #0d6efd !important;
            color: #fff !important;
            border-radius: 5px;
        }

        body {
            overflow-x: hidden;
        }
    </style>
}

Hethonglaptop_prj2/Hethonglaptop_prj2/Views/Admin/_DanhSachAccount.cshtml
@model IEnumerable<Hethonglaptop_prj2.Models.Account>

<div class="mb-3">
    <a class="btn btn-success" asp-area="" asp-controller="Accounts" asp-action="Create">
        <i class="fas fa-plus"></i> Thêm tài khoản
    </a>
</div>
<table class="table table-bordered table-hover">
    <thead class="table-dark">
        <tr>
            <th>ID</th>
            <th>UserName</th>
            <th>Email</th>
            <th>Role</th>
            <th>Hành động</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var acc in Model)
        {
            <tr>
                <td>@acc.AccountId</td>
                <td>@acc.UserName</td>
                <td>@acc.Email</td>
                <td>@acc.Role</td>
                <td>
                    <a class="btn btn-sm btn-warning" asp-controller="Accounts" asp-action="Edit" asp-route-id="@acc.AccountId">Sửa</a>
                    <a class="btn btn-sm btn-danger" asp-controller="Accounts" asp-action="Delete" asp-route-id="@acc.AccountId">Xóa</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Hethonglaptop_prj2/Hethonglaptop_prj2/Views/Admin/_DanhSachDonHang.cshtml
@model IEnumerable<Hethonglaptop_prj2.Models.HoaDon>

<div class="mb-3">
    <a class="btn btn-success" asp-area="" asp-controller="HoaDons" asp-action="Create">
        <i class="fas fa-plus"></i> Thêm đơn hàng
    </a>
</div>
<table class="table table-bordered table-hover">
    <thead class="table-dark">
        <tr>
            <th>Mã hóa đơn</th>
            <th>Ngày lập</th>
            <th>Khách hàng</th>
            <th>Tổng tiền</th>
            <th>Hành động</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var hd in Model)
        {
            <tr>
                <td>@hd.MaHd</td>
                <td>@hd.NgayLap.ToString("dd/MM/yyyy")</td>
                <td>@hd.MaKhNavigation?.HoTen</td>
                <td>@String.Format("{0:N0} VND", hd.TongTien)</td>
                <td style="width:160px;" class="text-center align-middle">
                    <div class="d-flex justify-content-center gap-2">
                        <a class="btn btn-primary" asp-area="" asp-controller="HoaDons" asp-action="Details" asp-route-id="@hd.MaHd">
                            <i class="fas fa-eye"></i>
                        </a>
                        <a class="btn btn-warning" asp-area="" asp-controller="HoaDons" asp-action="Edit" asp-route-id="@hd.MaHd">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="btn btn-danger" asp-area="" asp-controller="HoaDons" asp-action="Delete" asp-route-id="@hd.MaHd">
                            <i class="fas fa-trash"></i>
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

Hethonglaptop_prj2/Hethonglaptop_prj2/Views/Admin/_DanhSachKhachHang.cshtml
@model IEnumerable<Hethonglaptop_prj2.Models.KhachHang>

<div class="mb-3">
    <a class="btn btn-success" asp-area="" asp-controller="KhachHangs" asp-action="Create">
        <i class="fas fa-plus"></i> Thêm khách hàng
    </a>
</div>
<table class="table table-bordered table-hover">
    <thead class="table-dark">
        <tr>
            <th>Mã KH</th>
            <th>Tên KH</th>
            <th>Email</th>
            <th>SĐT</th>
            <th>Địa chỉ</th>
            <th>Hành động</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var kh in Model)
        {
            <tr>
                <td>@kh.MaKh</td>
                <td>@kh.HoTen</td>
                <td>@kh.Email</td>
                <td>@kh.Sdt</td>
                <td>@kh.DiaChi</td>
                <td style="width:160px;" class="text-center align-middle">
                    <div class="d-flex justify-content-center gap-2">
                        <a class="btn btn-primary" asp-area="" asp-controller="KhachHangs" asp-action="Details" asp-route-id="@kh.MaKh">
                            <i class="fas fa-eye"></i>
                        </a>
                        <a class="btn btn-warning" asp-area="" asp-controller="KhachHangs" asp-action="Edit" asp-route-id="@kh.MaKh">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="btn btn-danger" asp-area="" asp-controller="KhachHangs" asp-action="Delete" asp-route-id="@kh.MaKh">
                            <i class="fas fa-trash"></i>
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

Hethonglaptop_prj2/Hethonglaptop_prj2/Views/Admin/_DanhSachNhanVien.cshtml
@model IEnumerable<Hethonglaptop_prj2.Models.NhanVien>

<div class="mb-3">
    <a class="btn btn-success" asp-area="" asp-controller="NhanViens" asp-action="Create">
        <i class="fas fa-plus"></i> Thêm nhân viên
    </a>
</div>
<table class="table table-bordered table-hover">
    <thead class="table-dark">
        <tr>
            <th>Mã NV</th>
            <th>Họ tên</th>
            <th>Email</th>
            <th>Chức vụ</th>
            <th>Hành động</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var nv in Model)
        {
            <tr>
                <td>@nv.MaNv</td>
                <td>@nv.HoTen</td>
                <td>@nv.Email</td>
                <td>@nv.ChucVu</td>
                <td style="width:160px;" class="text-center align-middle">
                    <div class="d-flex justify-content-center gap-2">
                        <a class="btn btn-primary" asp-area="" asp-controller="NhanViens" asp-action="Details" asp-route-id="@nv.MaNv">
                            <i class="fas fa-eye"></i>
                        </a>
                        <a class="btn btn-warning" asp-area="" asp-controller="NhanViens" asp-action="Edit" asp-route-id="@nv.MaNv">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="btn btn-danger" asp-area="" asp-controller="NhanViens" asp-action="Delete" asp-route-id="@nv.MaNv">
                            <i class="fas fa-trash"></i>
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

Hethonglaptop_prj2/Hethonglaptop_prj2/Views/Admin/_DanhSachSanPham.cshtml
@model IEnumerable<Hethonglaptop_prj2.Models.SanPham>

<div class="mb-3">
    <a class="btn btn-success" asp-area="" asp-controller="SanPhams" asp-action="Create">
        <i class="fas fa-plus"></i> Thêm sản phẩm
    </a>
</div>
<table class="table table-bordered table-hover">
    <thead class="table-dark">
        <tr>
            <th>Mã sản phẩm</th>
            <th>Tên sản phẩm</th>
            <th>Giá</th>
            <th>Tồn kho</th>
            <th>Ảnh</th>
            <th>Hành động</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var sp in Model)
        {
            <tr>
                <td>@sp.MaSp</td>
                <td>@sp.TenSp</td>
                <td>@String.Format("{0:N0} VND", sp.Gia)</td>
                <td>@sp.SoLuong</td>
                <td>
                    <img src="@sp.Anh" alt="@sp.TenSp" style="width:80px;height:auto;" />
                </td>
                <td style="width:160px;" class="text-center align-middle">
                    <div class="d-flex justify-content-center gap-2">
                        <a class="btn btn-primary" asp-area="" asp-controller="SanPhams" asp-action="Details" asp-route-id="@sp.MaSp">
                            <i class="fas fa-eye"></i>
                        </a>
                        <a class="btn btn-warning" asp-area="" asp-controller="SanPhams" asp-action="Edit" asp-route-id="@sp.MaSp">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="btn btn-danger" asp-area="" asp-controller="SanPhams" asp-action="Delete" asp-route-id="@sp.MaSp">
                            <i class="fas fa-trash"></i>
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
    